#!/bin/bash
mysql -uroot -p$DBPASS < sql/dk_all_empty.sql

PICS=/tmp/digikam-debug-pics
[ -e $PICS ] && rm -r $PICS
mkdir -p $PICS/my-album
cp pics/* $PICS/my-album

mkdir -p config
cp template/digikamrc config

export XDG_CONFIG_HOME=$PWD/config
digikam
