DROP TABLE IF EXISTS PhotoSharing;
CREATE TABLE PhotoSharing
(imageid INTEGER PRIMARY KEY,
    remoteid LONGTEXT,
    CONSTRAINT PhotoSharing_Images FOREIGN KEY (imageid) REFERENCES Images (id) ON DELETE CASCADE ON UPDATE CASCADE,
    mtime_tags TIMESTAMP);

ALTER TABLE ImageTags
ADD mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ImageInformation
ADD mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

